/* v23.9 - targeted first-ground-contact landing correction
 * Keeps the v22.5 global physics and v23.8 diagnostics intact.
 * Only removes velocity/angular velocity that is newly generated by the
 * first ground collision when the piece was falling essentially straight.
 */
(() => {
  'use strict';

  if (typeof Physics === 'undefined' || typeof Matter === 'undefined' ||
      typeof Physics.step !== 'function') return;

  const originalStep = Physics.step;
  const pluginKey = 'v239LandingCorrection';

  function isPiece(body) {
    return !!body && !body.isStatic && body.label === 'piece';
  }

  function groundContact(body) {
    const pairs = Physics.engine && Physics.engine.pairs && Physics.engine.pairs.list
      ? Physics.engine.pairs.list : [];
    for (const pair of pairs) {
      if (!pair || !pair.isActive) continue;
      const a = pair.bodyA && pair.bodyA.parent ? pair.bodyA.parent : pair.bodyA;
      const b = pair.bodyB && pair.bodyB.parent ? pair.bodyB.parent : pair.bodyB;
      if ((a === body && b && b.label === 'ground') ||
          (b === body && a && a.label === 'ground')) return true;
    }
    return false;
  }

  Physics.step = function(dt) {
    const bodies = Physics.world && Physics.world.bodies ? Physics.world.bodies : [];
    const before = new Map();

    for (const body of bodies) {
      if (!isPiece(body)) continue;
      before.set(body.id, {
        vx: body.velocity.x,
        vy: body.velocity.y,
        av: body.angularVelocity,
        wasGrounded: !!(body.plugin && body.plugin[pluginKey] &&
                        body.plugin[pluginKey].grounded)
      });
    }

    originalStep(dt);

    for (const body of bodies) {
      if (!isPiece(body)) continue;

      body.plugin = body.plugin || {};
      const prev = before.get(body.id);
      const nowGrounded = groundContact(body);
      const prior = body.plugin[pluginKey] || {};
      const firstContact = nowGrounded &&
        !(prior.grounded || (prev && prev.wasGrounded));

      if (firstContact && prev) {
        const falling = prev.vy > 1.0;
        const nearlyStraight = Math.abs(prev.vx) < 0.35 &&
          Math.abs(prev.av) < 0.015;

        if (falling && nearlyStraight) {
          if (body.velocity.y < 0) body.velocity.y = 0;

          if (Math.abs(body.velocity.x - prev.vx) > 0.35) {
            body.velocity.x = prev.vx;
          }

          if (Math.abs(body.angularVelocity - prev.av) > 0.015) {
            body.angularVelocity = prev.av;
          }
        }
      }

      body.plugin[pluginKey] = {
        grounded: nowGrounded,
        corrected: !!firstContact && !!prev &&
          prev.vy > 1.0 &&
          Math.abs(prev.vx) < 0.35 &&
          Math.abs(prev.av) < 0.015
      };
    }
  };
})();
